apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vault
    vault_cr: vault
spec:
  size: {{ .Values.vault.size | default 3 }}
  image: {{ .Values.vault.image | default "hashicorp/vault:1.14.1" }}

  # ServiceAccount for Vault + bank-vaults configurer/unsealer
  serviceAccount: vault

  serviceType: ClusterIP

  # Annotations and labels
  vaultAnnotations:
    type/instance: vault
  vaultConfigurerAnnotations:
    type/instance: vaultconfigurer
  vaultLabels:
    example.com/log-format: json
  vaultConfigurerLabels:
    example.com/log-format: string

  # Raft storage using a PVC
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.vault.storage | default "1Gi" }}
        volumeMode: Filesystem
  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file

  # Distribute CA to webhook namespaces
  caNamespaces:
    - "vswh"
    - "default"
    - "demo"

  # Unseal configuration using Kubernetes secrets
  unsealConfig:
    options:
      preFlightChecks: true
      storeRootToken: true
      secretShares: 5
      secretThreshold: 3
    kubernetes:
      secretNamespace: {{ .Release.Namespace }}
      secretName: bank-vaults

  # Vault server configuration
  config:
    storage:
      raft:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: "https://vault.{{ .Release.Namespace }}:8200"
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    ui: true
    statsdDisabled: true
    serviceRegistrationEnabled: true

  # Resource limits and requests
  resources:
    vault:
      limits:
        memory: "512Mi"
        cpu: "200m"
      requests:
        memory: "256Mi"
        cpu: "100m"

  veleroEnabled: true

  # External Vault configuration - policies, auth methods, and secrets
  externalConfig:
    policies:
      - name: allow_secrets
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }

    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names:
              - default
              - vault-secrets-webhook
            bound_service_account_namespaces:
              - {{ .Release.Namespace }}
              - "vswh"
            policies: allow_secrets
            ttl: 1h
          - name: demo
            bound_service_account_names:
              - demo-sa
            bound_service_account_namespaces:
              - default
            policies: allow_secrets
            ttl: 1h

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2

    startupSecrets:
      - type: kv
        path: secret/data/accounts/aws
        data:
          data:
            AWS_ACCESS_KEY_ID: {{ .Values.vault.secrets.aws.accessKeyId | default "secretId" }}
            AWS_SECRET_ACCESS_KEY: {{ .Values.vault.secrets.aws.secretAccessKey | default "s3cr3t" }}
      - type: kv
        path: secret/data/dockerrepo
        data:
          data:
            DOCKER_REPO_USER: {{ .Values.vault.secrets.dockerrepo.user | default "dockerrepouser" }}
            DOCKER_REPO_PASSWORD: {{ .Values.vault.secrets.dockerrepo.password | default "dockerrepopassword" }}
      - type: kv
        path: secret/data/mysql
        data:
          data:
            MYSQL_ROOT_PASSWORD: {{ .Values.vault.secrets.mysql.password | default "s3cr3t" }}

  vaultEnvsConfig:
    - name: VAULT_LOG_LEVEL
      value: debug
