apiVersion: v2
name: bankvault
description: A Helm chart for installing bankvault
version: 0.10.5
appVersion: "v0.10.5"
dependencies:
  - name: vault-operator
    version: "1.23.0"
    repository: "oci://ghcr.io/bank-vaults/helm-charts"
    alias: vault-operator

  - name: vault-secrets-webhook
    version: "1.22.0"
    repository: "oci://ghcr.io/bank-vaults/helm-charts"
    alias: vault-secrets-webhook

    externalConfig:
    policies:
      - name: admin
        rules: |
          path "*" {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

    auth:
      - type: kubernetes
        path: kubernetes
        config:
          # Justera till din API-server om du kör annat än standard
          kubernetes_host: "https://kubernetes.default.svc:443"
        roles:
          - name: admin
            bound_service_account_names:
              - {{ .Values.vaultAdmin.serviceAccountName }}
            bound_service_account_namespaces:
              - {{ .Values.vaultAdmin.namespace | default .Release.Namespace }}
            policies:
              - admin
            ttl: "24h"
